### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Fimshed** [niklasr22/rpi5-ws2812#1]
f1mshed@raspberrypi:~ $ sudo apt install python3- rpi5-ws2812
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rpi5-ws2812

Why wont this work??? (Also sorry if this is just some basic/ common issue, but im a beginner with no clue what im doing)

**Comment by niklasr22** [comment]
Hi, the package is not available via the apt package manager but via the python pip package manager.

So you should follow the [preparation step in the readme file](https://github.com/niklasr22/rpi5-ws2812?tab=readme-ov-file#preparation) and than the perform the installation step `pip install rpi5-ws2812`.
